[package]
name = "ascii_art_processor"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24"
clap = { version = "4.4", features = ["derive"] }
walkdir = "2.4"
rayon = "1.8"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
colored = "2.0"
